package com.telepathdb.kpathindex.utilities;

import com.telepathdb.datamodels.Node;
import com.telepathdb.datamodels.Path;
import com.telepathdb.kpathindex.KPathIndex;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Utility to import graphs generated by gMark into the kpathindex.
 * gMark: https://github.com/graphMark/gmark
 */
public class GMarkImport {

  private final KPathIndex kPathIndex;

  public GMarkImport(KPathIndex kPathIndex) {
    this.kPathIndex = kPathIndex;
  }

  /**
   * Imports gMark file. Assumes the format of the file resembles:
   * 42 4 6
   * Where 42 and 6 are node ID's and 4 can be discarded.
   */
  public long doImport(String gMarkFile) throws IOException {

    long importedLines = 0;

    try(BufferedReader br = new BufferedReader(new FileReader(gMarkFile))) {
      String line = br.readLine();

      while (line != null) {
        // Split the line on space
        String[] split = line.split(" ");

        // First split is the starting node
        List<Node> nodes = new ArrayList<>(2);
        nodes.add(new Node(Long.parseLong(split[0])));
        // Second split is the end node
        nodes.add(new Node(Long.parseLong(split[2])));

        // Insert into the kpathindex
        kPathIndex.insert(new Path(importedLines, nodes));

        importedLines++;
        line = br.readLine();
      }
    }

    return importedLines;
  }
}
