sudo: false # false is faster
language: java
jdk:
  - oraclejdk8

# We'll just take a look at travis-ci.org
notifications:
  email: false

before_install:
  - pip install --user codecov # Codecov -> nice and smooth

after_success:
  - codecov # Codecov -> aight
